src/Entity/Propriete.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @UniqueEntity("titre")
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass="App\Repository\ProprieteRepository")
 */
class Propriete
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="imageName")
     */
    private $imageFile;

    /**
     * @ORM\OneToMany(targetEntity="Attachment", mappedBy="propriete", orphanRemoval=true, cascade={"persist"})
     */
    private $attachments;

    /**
     * @var \DateTime $updatedAt
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @var \DateTime $createdAt
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="5", max="255")
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min="10", max="1000")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $pieces;

    /**
     * @ORM\Column(type="integer")
     */
    private $chambres;

    /**
     * @ORM\Column(type="integer")
     */
    private $etages;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $chauffage;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $code_postal;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $vendu = false;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Critere", inversedBy="properties", cascade={"persist"})
     */
    private $criteres;

    /**
     * @Gedmo\Slug(fields={"titre"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="proprietes")
     */
    private $user;

    public function __construct()
    {
        $this->criteres = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->attachments = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->titre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->getTitre());

    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPieces(): ?int
    {
        return $this->pieces;
    }

    public function setPieces(int $pieces): self
    {
        $this->pieces = $pieces;

        return $this;
    }

    public function getChambres(): ?int
    {
        return $this->chambres;
    }

    public function setChambres(int $chambres): self
    {
        $this->chambres = $chambres;

        return $this;
    }

    public function getEtages(): ?int
    {
        return $this->etages;
    }

    public function setEtages(int $etages): self
    {
        $this->etages = $etages;

        return $this;
    }

    public function getChauffage(): ?string
    {
        return $this->chauffage;
    }

    public function setChauffage(string $chauffage): self
    {
        $this->chauffage = $chauffage;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getFormattedPrix(): string
    {
        return number_format($this->prix, 0, '', ' ');
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVendu(): ?bool
    {
        return $this->vendu;
    }

    public function setVendu(bool $vendu): self
    {
        $this->vendu = $vendu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @return Collection|Critere[]
     */
    public function getCriteres(): Collection
    {
        return $this->criteres;
    }

    public function addCritere(Critere $critere): self
    {
        if (!$this->criteres->contains($critere)) {
            $this->criteres[] = $critere;
            $critere->addProperty($this);
        }

        return $this;
    }

    public function removeCritere(Critere $critere): self
    {
        if ($this->criteres->contains($critere)) {
            $this->criteres->removeElement($critere);
            $critere->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName(): ?string
    {
        return $this->imageName;
    }


    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }


    public function setImageFile(?File $imageName = null)
    {
        $this->imageFile = $imageName;
        if ($imageName) {
            $this->updatedAt = new \DateTime('now');
        }

    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Attachment[]
     */
    public function getAttachments(): Collection
    {
        return $this->attachments;
    }

    public function getAttachment(): ?Attachment
    {
        if ($this->attachments->isEmpty()) {
            return null;
        }
        return $this->attachments->first();
    }

    public function addAttachment(Attachment $attachment): self
    {
        if (!$this->attachments->contains($attachment)) {
            $this->attachments[] = $attachment;
            $attachment->setPropriete($this);
        }

        return $this;
    }

    public function removeAttachment(Attachment $attachment): self
    {
        if ($this->attachments->contains($attachment)) {
            $this->attachments->removeElement($attachment);
            // set the owning side to null (unless already changed)
            if ($attachment->getPropriete() === $this) {
                $attachment->setPropriete(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }


}

src/Form/ProprieteType.php
<?php

namespace App\Form;

use App\Entity\Critere;
use App\Entity\Propriete;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ProprieteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('description',CKEditorType::class)
            ->add('surface')
            ->add('pieces')
            ->add('chambres')
            ->add('etages')
            ->add('chauffage')
            ->add('criteres', EntityType::class, [
                'class' => Critere::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false,
                'multiple' => true
            ])
            ->add('prix')
            ->add('adresse')
            ->add('ville')
            ->add('code_postal')
            ->add('vendu')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Propriete::class,
        ]);
    }
}

src/Controller/Admin/ProprieteController.php
<?php


namespace App\Controller\Admin;

use Doctrine\ORM\QueryBuilder;
use EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController;

class ProprieteController extends EasyAdminController
{
    protected function createListQueryBuilder($entityClass, $sortDirection, $sortField = null, $dqlFilter = null)
    {
        /**@var QueryBuilder $result */
        $result = parent::createListQueryBuilder($entityClass, $sortDirection, $sortField, $dqlFilter);
        if (method_exists($entityClass, 'getUser')) {
            $result->andWhere('entity.user = :user');
            $result->setParameter('user', $this->getUser());
        }
        return $result;
    }

    protected function createSearchQueryBuilder($entityClass, $searchQuery, array $searchableFields, $sortField = null, $sortDirection = null, $dqlFilter = null)
    {
        /** @var QueryBuilder $result */
        $result = parent::createListQueryBuilder($entityClass, $sortDirection, $sortField, $dqlFilter);
        if (method_exists($entityClass, 'getUser')) {
            $result->andWhere('entity.user = :user');
            $result->setParameter('user', $this->getUser());
        }
        return $result;
    }
}

src/Controller/ProprieteController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\PropertySearch;
use App\Entity\Propriete;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\ProprieteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ProprieteController extends AbstractController
{
    /**
     * @var ProprieteRepository
     */
    private $repository;

    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    public function __construct(ProprieteRepository $repository,EntityManagerInterface $entityManager, $twig)
    {
       $this->repository = $repository;
       $this->entityManager = $entityManager;
       $this->twig = $twig;
    }

    /**
     * @Route("/propriete", name="propriete")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $proprietes = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            12
        );

        return $this->render('propriete/index.html.twig', [
            'proprietes' => $proprietes,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="propriete.show2", requirements={"slug": "[a-z0-9\-]*"})
     * @param Propriete $propriete
     * @return Response
     */
    public function show(Propriete $propriete, string $slug, Request $request, ContactNotification $notification): Response
    {

        if ($propriete->getSlug() !== $slug) {
            return $this->redirectToRoute('propriete.show2', [
                'id' => $propriete->getId(),
                'slug' => $propriete->getSlug()
            ], 301);
        }

        $contact = new Contact();
        $contact->setPropriete($propriete);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);
            $this->addFlash('success', 'Votre email a bien été envoyé');
            return $this->redirectToRoute('propriete.show2', [
                'id' => $propriete->getId(),
                'slug' => $propriete->getSlug()
            ]);
        }

        return $this->render('propriete/show2.html.twig', [
            'propriete' => $propriete,
            'form' => $form->createView()
        ]);
    }
}

templates/propriete/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title 'Tous nos biens' %}
{% block body %}
    <div class="jumbotron text-center">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.criteres) }}
                </div>
                <div class="col">
                    {{ form_row(form.city) }}
                </div>
                <div class="col">
                    <div class="form-group">
                    <button class="btn btn-default">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container">
        <h2>Les derniers biens</h2>
        <div class="row flex">
            {% for propriete in proprietes %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        {% if propriete.imagename %}
                            <img src="{{ vich_uploader_asset(propriete, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
                        {% else %}
                            <img src="{{ '/proprietes/empty.jpg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{{ path('propriete.show', {id: propriete.id, slug: propriete.slug}) }}">{{ propriete.titre }}</a>
                            </h5>
                            <p class="card-text">{{ propriete.description  | raw }}</p>
                            <p class="card-text">{{ propriete.surface }} m2 - {{ propriete.ville }} ({{ propriete.codePostal }})</p>
                            <div class="text-danger"
                                 style="font-weight: bold; font-size: 2rem">{{ propriete.formattedPrix }} €
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="pagination">
        {{ knp_pagination_render(proprietes) }}
    </div>
    </div>

{% endblock %}

templates/propriete/show.html.twig
{% extends 'base_admin.html.twig' %}

{% block title propriete.titre %}

{% block body %}
    <div class="jumbotron">
        <div class="container">

            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}

            {% if not form.vars.valid %}
                <div class="alert alert-danger">
                    Erreur ! veuillez entrer une adresse mail valide
                </div>
            {% endif %}

            <div class="row">
                <div class="col-md-8">
                    <div data-slider>
                    {% if propriete.imagename %}
                        <img src="{{ vich_uploader_asset(propriete, 'imageFile') | imagine_filter('medium') }}"
                             alt="card-img-top" style="width: 100%; height: auto">
                    {% else %}
                        <img src="{{ '/uploads/images/proprietes/empty.jpg' | imagine_filter('medium') }}"
                             alt="card-img-top" style="width: 100%; height: auto">
                    {% endif %}
                </div>
            </div>
                <div class="col-md-4">
                    <h1>{{ propriete.titre }}</h1>
                    <h2>{{ propriete.pieces }} pièces - {{ propriete.surface }} m2</h2>
                    <div class="text-danger" style="font-weight: bold; font-size: 2rem">{{ propriete.formattedPrix }}€
                    </div>
                    <a href="#" class="btn btn-default" id="contactButton"{% if form.vars.submitted %} style="display: none;"{% endif %}>Contacter l'agence</a>
                    <div id="contactForm" class="mt-4"{% if not form.vars.submitted %} style="display: block;"{% endif %}>
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col">{{ form_row(form.firstname) }}</div>
                            <div class="col">{{ form_row(form.lastname) }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form_row(form.phone) }}</div>
                            <div class="col">{{ form_row(form.email) }}</div>
                        </div>
                        {{ form_rest(form) }}
                        <div class="form-group">
                            <button class="btn btn-default">Envoyer</button>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <div class="col-md-12">
            <p>
                {{ propriete.description | raw }}
            </p>
        </div>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ propriete.surface }} m2</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ propriete.pieces }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ propriete.chambres }}</td>
                    </tr>
                    <tr>
                        <td>Étage</td>
                        <td>{{ propriete.etages }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ propriete.chauffage }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Critères</h2>
                <ul class="list-group">
                    {% for critere in propriete.criteres %}
                        <li class="list-group-item">{{ critere.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/propriete/show2.html.twig
{% extends 'base_site.html.twig' %}
    {% block body %}

        <style>

            .property-gallery{
                padding: 0px;
                max-width: 900px;
            }

            .property-gallery-slide {
                /*border: 3px solid red;*/

                background-position: center center;
                background-repeat: no-repeat;
                height: 572px;
                position: relative;
                display: none;
            }

            .Thumbnails {
                /*border: #5f3f3f 3px solid;*/
                position: relative;
                display: flex;
                flex-direction: column;
                /*justify-content: center;*/
                flex-wrap: wrap;
                height: 600px;
                /*overflow: scroll;*/

            }

            .Thumbnails img {
                /*display: none;*/
                max-width: 100px;

                opacity: 0.6;
            }

            .Thumbnails img:hover {
                /*display: none;*/
                max-width: 100px;
                opacity: 1;

            }

            /*.property-thumbnail {*/
            /*    margin: 0px;*/
            /*}*/

            .property-thumbnail {
                cursor: pointer;
                margin:5px;
            }

            .property-gallery a,
            .property-gallery:hover{
                color: white;
                font-weight: bold;
                font-size: 20px;
            }



            /* Next & previous buttons */
            .property-prev,
            .property-next {
                cursor: pointer;
                position: absolute;
                top: 50%;
                width: auto;
                padding: 16px;
                margin-top: -50px;
                border-radius: 0 3px 3px 0;
                user-select: none;
                -webkit-user-select: none;
            }

            /* Position the "next button" to the right */
            .property-next {
                right: 0;
                border-radius: 3px 0 0 3px;
            }

            /* On hover, add a black background color with a little bit see-through */
            .property-prev:hover,
            .property-next:hover {
                background-color: rgba(148, 112, 84, 0.8);
            }

            .property-slide-parallax {
                min-height: 400px;
                background-attachment: fixed;
                background-position: bottom;
                background-repeat: no-repeat;
                background-size: cover;
            }


        </style>


        <!-- Preloader -->
        <div id="preloader">
            <div class="south-load"></div>
        </div>

        <!-- Top and NavBar -->
        <header class="header-area">
            {% include 'Site/include/headerTop.html.twig' %}
            {% include 'Site/include/headerNavBar.html.twig' %}
        </header>

        <!-- Side -->
        <section class="hero-area section-padding-0-100">
            <div class="property-slide-parallax " style="background-image: url('{{asset('build/images/bg-img/feature1.90201ff9.jpg')}}');"></div>
        </section>

        <!-- Search Area -->
        <section class="south-search-area" >
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="advanced-search-form" style="top:-300px">
                            <div class="container-fluid " style="margin-top: 20px" >
                                <div class="row justify-content-center">

                                    <div class="col-10 property-gallery" style="">
                                        <div class="property-gallery-slide" style="background-image: url('{{ vich_uploader_asset(propriete, 'imageFile') }}');"></div>
                                        <div class="property-gallery-slide" style="background-image: url('{{asset('build/images/bg-img/feature8.965af860.jpg')}}');"></div>
                                        <div class="property-gallery-slide" style="background-image: url('{{asset('build/images/bg-img/feature3.4bed2344.jpg')}}');"></div>
                                        <div class="property-gallery-slide" style="background-image: url('{{asset('build/images/bg-img/feature4.ef4ca563.jpg')}}');"></div>
                                        <div class="property-gallery-slide" style="background-image: url('{{asset('build/images/bg-img/feature5.b1a30f2c.jpg')}}');"></div>
                                        <div class="property-gallery-slide" style="background-image: url('{{asset('build/images/bg-img/feature6.2191f756.jpg')}}');"></div>
                                        <div class="property-gallery-slide" style="background-image: url('{{asset('build/images/bg-img/feature7.f3787324.jpg')}}');"></div>

                                        <a class="property-prev" onclick="plusSlides(-1)">❮</a>
                                        <a class="property-next" onclick="plusSlides(1)">❯</a>
                                    </div>

                                    <div class="col-1 Thumbnails" style="margin-right: 33px; ">
                                        <img class="property-thumbnail" src="{{ vich_uploader_asset(propriete, 'imageFile') }}" onclick="currentSlide(1)" alt="">
                                        <img class="property-thumbnail" src="{{asset('build/images/bg-img/feature8.965af860.jpg')}}" onclick="currentSlide(2)" alt="">
                                        <img class="property-thumbnail" src="{{asset('build/images/bg-img/feature3.4bed2344.jpg')}}" onclick="currentSlide(3)" alt="">
                                        <img class="property-thumbnail" src="{{asset('build/images/bg-img/feature4.ef4ca563.jpg')}}" onclick="currentSlide(4)" alt="">
                                        <img class="property-thumbnail" src="{{asset('build/images/bg-img/feature5.b1a30f2c.jpg')}}" onclick="currentSlide(5)" alt="">
                                        <img class="property-thumbnail" src="{{asset('build/images/bg-img/feature6.2191f756.jpg')}}" onclick="currentSlide(6)" alt="">
                                        <img class="property-thumbnail" src="{{asset('build/images/bg-img/feature7.f3787324.jpg')}}" onclick="currentSlide(7)" alt="">
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>

        <!-- Search Area End -->


        <script>
            let slideIndex = 1;
            showSlides(slideIndex);

            function plusSlides(n) {
                showSlides(slideIndex += n);
            }

            function currentSlide(n) {
                showSlides(slideIndex = n);
            }

            function showSlides(n) {

                let slides = document.getElementsByClassName("property-gallery-slide");
                let dots = document.getElementsByClassName("property-thumbnail");

                if (n > slides.length) {slideIndex = 1}

                if (n < 1) {slideIndex = slides.length}

                for (let i = 0; i < slides.length; i++) {
                    slides[i].style.display = "none";
                }
                for (let i = 0; i < dots.length; i++) {
                    dots[i].className = dots[i].className.replace(" active", "");
                }

                slides[slideIndex-1].style.display = "block";
                dots[slideIndex-1].className += " active";
            }
        </script>







{% endblock %}